apiVersion: ccm.harness.io/v1
kind: WorkloadDistributor
metadata:
  name: grafana-wld
spec:
  workloads:
    - name: grafana-deployment
      namespace: apps
      type: Deployment
      baseOndemandCapacity: 2
  distribution:
    spot: 6
    ondemand: 2
